### ISSUE TITLE
Is there a way to put multiple conditions with condition_position()?

### ISSUE THREAD

**Issue by famora2** [dfki-ric/movement_primitives#21]
Hi,

is there a way to put multiple conditions such as pass position_mean1 at t=0 and position_mean2 at t=1? 

Thank you.

**Comment by AlexanderFabisch** [comment]
Hi @famora2 ,

the function returns a new ProMP. Of course it should be possible to call the same function on this ProMP object. Maybe the variance will be quite small in the end. Let me know if it works for you or if you have any problems!
