### ISSUE TITLE
CartesianDMP object has no attribute forcing_term

### ISSUE THREAD

**Issue by buschbapti** [dfki-ric/movement_primitives#3]
I would like to save the weights of a trained `CartesianDMP`. There is no overloaded function `get_weights()` so I guess the one from the `DMP` base class should work. However, when calling it it raises the error in the title:

```console
AttributeError: 'CartesianDMP' object has no attribute 'forcing_term'
```

Do you know what could be the issue here? Thanks in advance.

**Comment by buschbapti** [comment]
Actually I think I have found the issue. The `get_weights` function actually uses the following:

```python
def get_weights(self):
        """Get weight vector of DMP.
        Returns
        -------
        weights : array, shape (6 * n_weights_per_dim,)
            Current weights of the DMP.
        """
        return np.concatenate(self.forcing_term.weights_pos.ravel(),
                                            self.forcing_term_rot.weights.ravel())
```

However, the attributes of the class are `forcing_term_pos` and `forcing_term_rot`. I will create a PR to address this.

**Comment by AlexanderFabisch** [comment]
Thanks for the contribution!

There was an another problem with the `get_weights`. It is tested and should work now.

**Comment by buschbapti** [comment]
Yes indeed a `TypeError` as well due to the missing double parentheses. Thanks for correcting that.
