### ISSUE TITLE
JOSS suggestion: Summary

### ISSUE THREAD

**Issue by gautam-sharma1** [dfki-ric/movement_primitives#46]
It will be good to add a figure describing what exactly the movement primitives are trying to learn or imitate for non specialist audience. It can be a graph similar to the one in the README. Something to let the reader visually know what the goal policy is that the movement primitives are trying to imitate.

**Comment by AlexanderFabisch** [comment]
That's a good idea. I made a figure illustrating the imitation learning process to the readme and the paper. I will close the issue, but feel free to open it if you have additional comments.
