### ISSUE TITLE
Exposing the alpha/beta parameters

### ISSUE THREAD

**Issue by cmower** [dfki-ric/movement_primitives#57]
Hi, I am wondering if it is possible to expose [`alpha_y` and `beta_y`](https://github.com/dfki-ric/movement_primitives/blob/fa89340bb43fa485f5a543188b8f1afe4bf74fc5/movement_primitives/dmp/_dmp.py#L419-L420) to `__init__`?  Also, would it make sense for these to be arrays rather than scalars so the user could weight individual dimensions?

**Comment by AlexanderFabisch** [comment]
Hi @cmower ,

I'm not against it. Do you mean for all DMP flavors or just the standard DMP? Would you be interested in working on a pull request for this?

**Comment by cmower** [comment]
Yes, happy to work on a PR. I'll modify all flavours.

**Comment by AlexanderFabisch** [comment]
Great, thank you, I'm happy to review it.

**Comment by cmower** [comment]
Hi @AlexanderFabisch, PR submitted https://github.com/dfki-ric/movement_primitives/pull/59
